# Configured by: booth config --no-tui --overwrite --variant xfce --port 10000 --select python+kernel~pip-config/notebook/xfce/claude-code~credential~settings-cache

variant = "xfce"
port = "10000"

run-args = ["-e", "PYTHONDONTWRITEBYTECODE=1"]
